version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "27017:27017"
    networks:
      - ecommerce-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    depends_on:
      - mongo
    ports:
      - "2181:2181"
    networks:
      - ecommerce-network
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - ecommerce-network
    depends_on:
      - zookeeper

  product-service:
    image: mateushcds/ecommerce-product-service
    restart: always
    build: ./product-service
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
      SPRING.APPLICATION.NAME: product-service
      SPRING.PROFILES.ACTIVE: dev
    depends_on:
      - kafka
    networks:
      - ecommerce-network
    ports:
      - "8080:8080"
    command: mvn spring-boot:run

networks:
  ecommerce-network:
    driver: bridge

