spring:
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: kafka:9093
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce_db
    username: mateuzzo
    password: payment123*
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
port: 8081