name: CI-DEV-ENV

on:
  push:
    branches: [ "dev" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

          
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
      
    - name: Build Application JAR
      working-directory: ./product-service
      run: mvn clean package

    - name: Docker Compose Build
      run: docker compose up build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/ecommerce-product-service:latest ${{ secrets.DOCKER_USERNAME }}/ecommerce-product-service:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-product-service:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-product-service:latest
